# Generated by Django 5.0.6 on 2024-09-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="feedback",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], max_length=3
            ),
        ),
    ]
