# Generated by Django 5.0.6 on 2024-09-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="university_logos/")),
                (
                    "type",
                    models.CharField(
                        choices=[("PUB", "Public"), ("PRI", "Private")],
                        default="PUB",
                        max_length=3,
                    ),
                ),
                ("card_image", models.ImageField(upload_to="university_cards/")),
                ("banner", models.ImageField(upload_to="university_banners/")),
                ("map_location", models.URLField()),
                ("twitter", models.URLField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Universities",
            },
        ),
    ]
