# Generated by Django 5.0.6 on 2024-09-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='type',
            field=models.CharField(choices=[('PUB', 'Public'), ('PRI', 'Private')], default='PUB', max_length=10),
        ),
    ]
