# Generated by Django 5.0.6 on 2024-09-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_aboutparagraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicprogram',
            name='description',
        ),
        migrations.RemoveField(
            model_name='university',
            name='description',
        ),
    ]
